services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mon_broker_mqtt
    ports:
      - "1884:1883" # MQTT -> hôte:1884
      - "9002:9001" # WebSockets -> hôte:9002
    volumes:
      - ./mosquitto_config:/mosquitto/config:rw
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mon_serveur_nginx
    ports:
      - "8080:80" # HTTP -> hôte:8080
      - "4443:443" # HTTPS -> hôte:4443
    volumes:
      - ./nginx_html:/usr/share/nginx/html # Fichiers statiques

  grafana:
    image: grafana/grafana
    container_name: mon_grafana
    ports:
      - "3000:3000" # Grafana -> hôte:3000
    volumes:
      - ./grafana_data:/var/lib/grafana # Persistance des données
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Mot de passe admin par défaut
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: mon_influxdb
    ports:
      - "8086:8086" # InfluxDB -> hôte:8086
    environment:
      INFLUXDB_DB: historisation_db
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
