# Utiliser l'image officielle Nginx
FROM nginx:latest

# Copier vos fichiers HTML et JS dans le dossier web de Nginx
COPY index.html /usr/share/nginx/html/

# Exposer le port 80 pour accéder à Nginx via le navigateur
EXPOSE 80